Feature scan
ppsucweb/wechat-practice pull request #2
Opened 2019-02-06 12:15 UTC by LWD666

本次更新包括扫一扫页面（实现创建扫码控件，扫码成功并返回二维码类型和内容，但是style略有不足，日后更新补足），摇一摇页面（实现摇一摇音效和动画，缺陷是没有还原动画），彩蛋页面（缺陷是让人看着晕哈哈哈哈），至此第二阶段任务完成！

2019-02-06 12:19 UTC, jerryOnlyZRJ requested changes
尽快做出修改

2019-02-06 12:19 UTC, jerryOnlyZRJ commented on css/shark.css
> +html
代码提交之前都应当可视化增加可读性！

2019-02-06 13:01 UTC, LWD666 commented on css/shark.css
> +html
收到！

2019-02-06 14:04 UTC, jerryOnlyZRJ requested changes
总体而言是基本实现了要求，但是也还存在一些问题：包括script标签的位置，代码的格式化，还有一些在本次CD中提到的小瑕疵，习惯需要慢慢养成，代码格式化每个IDE也都有提供相关的功能，在Hbuilder中，直接在代码栏内右键 -> 重排代码格式（或者在菜单栏中“编辑” -> 重排代码格式）都可以自动格式化代码，每次写完代码都可以执行一次格式化，增加代码工整度。
本次提出的建议全部修改后将合并入master。

2019-02-06 14:04 UTC, jerryOnlyZRJ commented on css/surprise.css
> +	transform-style: preserve-3d;
加一个 `backface-visibility: hidden;` 属性，就不会有透视的感觉

2019-02-06 14:04 UTC, jerryOnlyZRJ commented on html/find.html
>  		<script type="text/javascript" charset="utf-8">
这个 `script` 标签可以和下面一个标签合为一个

2019-02-06 14:04 UTC, jerryOnlyZRJ commented on html/father.html
>  		<script src="../js/mui.min.js"></script>
我们一般不把 `script` 标签放在 `head` 标签里，而是放在 `body` 标签的底部，所以以后应当养成这样的习惯

2019-02-06 14:04 UTC, jerryOnlyZRJ commented on html/father.html
>  		<title></title>
`title` 标签我们一般不会放空，可以填写该页面的名称

2019-02-06 14:04 UTC, jerryOnlyZRJ commented on css/surprise.css
> +
为什么这边有这么多空行？

2019-02-06 14:04 UTC, jerryOnlyZRJ commented on html/find.html
> +						<img class="mui-media-object mui-pull-left" src="../img/PYQ.png" style="height: 20px;width: 20px;margin-top:8px;" />
如果一个页面有独立的样式可以为页面建立一个单独的CSS文件

2019-02-06 14:04 UTC, jerryOnlyZRJ commented on html/find.html
> +		</script>
有没发现这个script标签里大多数代码是重复的？可以通过这样的方法优化：
```
function openWindow(filename, id){
    mui.openWindow({
	url: filename,
	id: id
    });
}
```
然后绑定事件的时候，只需要：
```
<li class="mui-table-view-cell text1" onclick="openWindow('surprise.html', 'surprise')">
```

2019-02-06 14:04 UTC, jerryOnlyZRJ commented on html/find.html
> +				<li class="mui-table-view-cell text1" onclick="open_win()">
onclick绑定不传参的方法时，一般不写括号

2019-02-06 14:04 UTC, jerryOnlyZRJ commented on html/scan.html
> +			var scan = null;
为什么这里要生命一个scan变量？在 `startRecognize` 函数体里生命不是也没有问题？

2019-02-06 14:04 UTC, jerryOnlyZRJ commented on html/scan.html
> +		<script type="text/javascript">
这里的代码也可以一起塞到body底部的那个标签中

2019-02-07 03:20 UTC, jerryOnlyZRJ approved these changes

2019-02-07 03:21 UTC, merged